
server:
  port: 8081
spring:
  application:
    name: pms-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/guli_pms?useUnicode=true&characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 123456

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml  # \u8BFB\u53D6\u6620\u5C04\u6587\u4EF6
  global-config:
    db-config:
      id-type: auto  # \u9ED8\u8BA4\u4F7F\u7528\u6570\u636E\u5E93\u81EA\u589E


